### ISSUE TITLE
报错relocation R_X86_64_TPOFF32 against `_ZN3NTLL8iodigitsE' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by xitingrimu** [SKLC-FHE/CHIFHE#1]
make编译时报错relocation R_X86_64_TPOFF32 against `_ZN3NTLL8iodigitsE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
请问如何解决？

我在网络上查询了相关解决方法，但似乎都没有什么用处，我对cmake指令不太熟悉，希望能得到您的帮助。

**Comment by Wangkaixing** [comment]
这似乎是NTL库兼容性问题，openfhe文档中指出“A regular binary install (using tools like apt-get) will not work Special compilation flags need to be passed. See [Instructions for installing GMP and NTL](https://openfhe-development.readthedocs.io/en/latest/sphinx_rsts/intro/installation/gmp_ntl.html#gmp-ntl-install)”。请参考链接，并在重启后再次尝试。

**Comment by xitingrimu** [comment]
非常感谢您的及时回复，的确是NTL库版本的问题。已经能够正常运行了。再次感谢您的帮助。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SKLC-FHE/CHIFHE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月10日(星期五) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SKLC-FHE/CHIFHE] 报错relocation R_X86_64_TPOFF32 against `_ZN3NTLL8iodigitsE' can not be used when making a shared object; recompile with -fPIC (Issue #1)





 
这似乎是NTL库兼容性问题，openfhe文档中指出“A regular binary install (using tools like apt-get) will not work Special compilation flags need to be passed. See Instructions for installing GMP and NTL”。请参考链接，并在重启后再次尝试。
